export const PROJECT_STUDENT_DETEALIS = 'PROJECT_STUDENT_DETEALIS';
export const TOTAL_DETAILS = 'TOTAL_DETAILS';
export const DELETE_STUDENT_DETEAILS = 'DELETE_STUDENT_DETEAILS';
export const VIEW_STUDENT_DETAILS = 'VIEW_STUDENT_DETAILS';
export const REFRESH_PROJECT_STUDENT_DETEALIS = 'REFRESH_PROJECT_STUDENT_DETEALIS';
